### ISSUE TITLE
configure shadowd with nginx for laravel project

### ISSUE THREAD

**Issue by yeslem41** [zecure/shadowd_php#54]
hi everyone i'm working on deploy laravel project on docker and use shadowd as waf, laravel project work probly on docker with nginx but when i try to configure show i find this output
![image](https://user-images.githubusercontent.com/65510899/171178018-c8fbf94d-bcca-4913-8f4f-6726918f0bc4.png)

nginx configuration:
```
server {
    listen 80;
    listen [::]:80;
    server_name localhost;
    root /var/www/html/public;
 
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";
    index index.php;
    charset utf-8;
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }
 
    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }
 
    error_page 404 /index.php;
 
    location ~ \.php$ {
        fastcgi_pass php:9000;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param  PHP_ADMIN_VALUE  "auto_prepend_file=/usr/share/shadowd/shadowd.php";
        include fastcgi_params;
    }
 
    location ~ /\.(?!well-known).* {
        deny all;
    }
}
```
my docker compose
```
version: "3.9" # optional since v1.27.0
networks:
  laravel:
services:
  nginx:
    image: nginx:stable-alpine
    container_name: laravel_nginx
    ports:
      - "8088:80"
    volumes:
      - "./:/var/www/html"
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    # depends_on:
    #   - php
    #   - mysql
    networks:
      - laravel

  mysql:
    image: mysql:8
    container_name: laravel_mysql
    ports:
      - "3366:3306"
    volumes:
      - "./mysql:/var/lib/mysql"
    restart: unless-stopped
    tty: true
    environment:
      - MYSQL_DATABASE=ttDataBase
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - SERVICE_TAGS=dev
      - MYSQL_SERVICE_NAME=mysql
    networks:
      - laravel
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_php
    ports:
      - "9000:9000"
    volumes:
      - "./:/var/www/html"
    networks:
      - laravel

```
dockerfile

```
FROM php:8.0.3-fpm-alpine3.12
RUN docker-php-ext-install pdo pdo_mysql
RUN apk add libzip-dev
RUN docker-php-ext-install zip
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
```

two networks are on docker :
![image](https://user-images.githubusercontent.com/65510899/171178725-1ac66e23-258f-4665-8ad4-7fec84e0f6f1.png)

please someone help me.
